#spring:
#  application:
#    name: PAYMENT-SERVICE
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#
#    consumer:
#      group-id: payment-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
